### ISSUE TITLE
Section areas titles

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-module-participatory-documents#27]
NOTE: What we've been calling groups or zones will be named officially "Sections"

- [x] Open a little modal define the title of a section (formerly a group or a zone). No description is needed.
  Mockup:
  ![image](https://user-images.githubusercontent.com/1401520/207841692-586a5492-e0d5-45fb-bd0b-fcaa108f92e3.png)
- [x] Allow to delete the section and all the boxes related when the "delete" button is pressed, ask for confirmation.
- [x] Remove the current "description"
- [x] Add a new method to the "zone" model (see #29 ) to return the title translated with this logic:
  - [x] If a title is defined, return that according to language
  - [x] If a title is not defined, return a generic title named "Section #n"), where **n** is a consecutive integer ordered according the order of creation of the section (or the position of the first box related in the document).
- [x] Show this title in the modal title
- [x] Tests

**Comment by alecslupu** [comment]
Let's a field to keep the N regarding the section, and recalculate the number when the document is being published. 
There may be some issues in the admin logs section understanding what is the affected section. 
@microstudi to clarify with client.
