### ISSUE TITLE
Create the answering controller in the admin

### ISSUE THREAD

**Issue by microstudi** [openpoke/decidim-module-participatory-documents#32]
In #28 we list the suggestions made in the document. The button in each suggestion that allows to answer the proposal should bring the admin here.

- [x] Create the controller and views for view in detail a suggestion.
- [x] Display the suggestion full text
- [x] Add a "respond" field form.
- [x] Handle the "respond" action simiilarly as currently the admin responds a proposal (note: decide if we use the same "suggestions" table for responses or create a new one). We don't need to create "conversations like" threads here. Each suggestion has one or more responses but this responses cannot have a reply by the user, instead the user will be able to make an additional suggestion (see #31). No need for RICHTEXT.
- [x] It should be a checkbox named as "Draft", if clicked the response should not be published in the public side yet.
- [ ] The "status" of the response should follow this logic:
  - [ ] If there's and answer and the status is "draft", status is "Draft"
  - [ ] If there's and answer and "draft" is not marked, status is "Answered"
  - [ ] If there's no answer, status is "Not answered"
- [ ] In the public sidebar, add the status of the response (if any, excepting draft).
- [x] Use papertrail for the responses

Mockup (the status of the response is NOT accurated, should be a checkbox with "draft"):
![imatge](https://user-images.githubusercontent.com/40388743/207906597-1891eefd-314b-4ecf-86bf-e0373b1e5f1a.png)

**Comment by alecslupu** [comment]
Implemented as : 
![image](https://user-images.githubusercontent.com/105683/213824124-a2d0d8df-ffe8-4209-b151-468ab844e382.png)

**Comment by alecslupu** [comment]
The following section from requirements, is moved to be as part of #33 , as there is more suitable for ease of testing

- [ ] The "status" of the response should follow this logic:
  - [ ] If there's and answer and the status is "draft", status is "Draft"
  - [ ] If there's and answer and "draft" is not marked, status is "Answered"
  - [ ] If there's no answer, status is "Not answered"
- [ ] In the public sidebar, add the status of the response (if any, excepting draft).
